[workspace]

members = [
    "errors",
    "env",
    "logging",
    "mqtt",
    "amqp",
    "postgres",
    "traces",
    "metrics",
    "httpw",
    "health_readiness",
    "secrets_manager",
]

default-members  = [
    "errors", 
    "env", 
    "logging", 
    "mqtt", 
    "amqp", 
    "postgres",
    "traces",
    "metrics",
    "httpw",
    "health_readiness",
    "secrets_manager",
]
