[workspace]
resolver = "2"

members = [
    "messaging",
    "rabbitmq",
    "auth",
    "configs",
    "configs_builder",
    "health_readiness",
    "http_components",
    "http_server",
    "tiny_server",
    "logging",
    "metrics",
    "migrator",
    "mqtt",
    "mqttv2",
    "otel",
    "secrets_manager",
    "sql_pool",
    "traces",
]