[package]
name = "logging"
version = "0.1.0"
edition = "2021"

[dependencies]
errors = { path = "../errors" }
env = { path = "../env" }
tracing-bunyan-formatter = { version = "0.3.3" }
tracing-subscriber = { version = "0.3.15" }
tracing-log = { version = "0.1.3" }
tracing-appender = { version = "0.2.2" }
tracing = { version = "0.1.35" }