[package]
name = "mqtt"
version = "0.1.0"
edition = "2021"

[dependencies]
errors = { path = "../errors" }
env = { path = "../env" }
otel = { path = "../otel" }
opentelemetry = { version = "0.17.0" }
log = { version = "0.4.17" }
async-trait = { version = "0.1.56" }
rumqttc = { version =  "0.13.0" }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = { version = "1.0.82" }
bytes = { version = "1.2.0", features = ["serde"] }

[dev-dependencies]
mockall = { version = "0.11.2" }
tokio = { version = "1.17.0" }