[package]
name = "amqp"
version = "0.1.0"
edition = "2021"

[dependencies]
errors = { path = "../errors" }
env = { path = "../env" }
otel = { path = "../otel" }
lapin = { version = "2.1.1" }
opentelemetry = { version = "0.17.0" }
uuid = { version = "1.1.2", features = ["v4"] }
async-trait = { version = "0.1.56" }
log = { version = "0.4.17" }
serde_json = { version = "1.0.82" }
serde = { version = "1.0.140", features = ["derive"] }
