[package]
name = "metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
env = { path = "../env" }
errors = { path = "../errors" }

tokio = { version = "1.23.0", features = ["default"] }
opentelemetry = { version = "0.18.0", features = ["rt-tokio", "metrics"] }
tracing = { version = "0.1.37" }

tonic = { version = "0.8.3", features = ["tls"] }
opentelemetry-otlp = { version = "0.11.0", features = ["tonic", "metrics", "grpc-tonic" , "tls", "tls-roots"] }

opentelemetry-prometheus = { version = "0.11.0" }
prometheus = { version = "0.13.3" }
actix-web = { version = "4.2.1" }